# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '8c54346d-1853-4c37-b92b-772903dda648'
  imageRepository: 'chatnet'
  containerRegistry: 'elipse.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Elipse/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test stage
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)
    steps:
    # ...
    # do this after other tasks such as building
    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: latest
        arguments: --label buildtype=nightly

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: latest
