---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: mssql
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30306
      name: tcpsql